name: cwtc
description: Legacy WoW Talent Calculator.
publish_to: 'none'

version: 1.1.0+16

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter_icons:
    android: true
    ios: true
    image_path: 'assets/images/icons/app_icon.jpg'

dependencies:
  flutter:
    sdk: flutter

  # state management
  stacked: ^2.2.7
  stacked_services: ^0.8.15
  stacked_hooks: ^0.2.1
  shared_preferences: ^2.0.8
  wow_talent_calculator: ^1.0.3
    # path: C:/dev/workspace/dart/wow_talent_calculator/

  # widgets
  align_positioned: ^3.0.0
  flutter_speed_dial: ^4.6.6

  # inversion of control
  injectable: ^1.5.0

  # DB
  sqflite: ^2.0.0+4

  # Utils
  path_provider: ^2.0.6
  rainbow_color: ^2.0.1
  url_launcher: ^6.0.12
  share: ^2.0.4

  # Ads
  google_mobile_ads: ^0.13.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # ios build fix due to old deps
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Icons
  flutter_launcher_icons: ^0.9.2

  # runner
  build_runner: ^2.1.4

  # generators
  stacked_generator: ^0.5.5
  injectable_generator: ^1.5.2

  flutter_lints:

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/images/arrows/
    - assets/images/bgs/
    - assets/images/icons/

  fonts:
    - family: LifeCraft
      fonts:
        - asset: assets/fonts/LifeCraft.ttf